language: java
jdk:
  - oraclejdk8
before_install:
 - chmod +x gradlew

addons:
  sonarqube: true
env:
  global:
    - secure: P4vbtMFXVtpKKXAs7P4Aicv2TzArXpWk03hMMzj0kGtdlPoTxXhahCVL1W/isGq7OZFoUA0yU7ynos8XfLSpVZJ8Nal/F/g4pXH/5ntotiHQdWWyzuF+0gKncrtAJybDgJQAaB7ZfrpvgZSoN1UwgoVtJNONcc0gm66kRx4vaenJh310G/COdwXA/uW0J4sbGPO27/XApvd7PwUyL0X/dO0c82Qm0emtT7zxl+rUaymCWR5/FNL7/vfZVsBEBqog1Ig6h51nVBOQNRzb7ARu49n5NwzyzbyuKiMtX64qTjlQJ7prvAUdvRQ7SR9yFhBXWrWEz+b4TeWL+CnT4odjsK0GHM5Z3PGygov+EQMyyy1vsqAX3CCfhOAEE+BVdrR1HVGMVPa4XTK1+5EyjOWQ6WrjEsninpqGDJIJTCtyVQA/4WGVR1v1xGLFB25MkENeeN+0u1r1bNJvrf0oaBPBPQIyu3o/ErE3Q5VGqpJg/J5duNuI/CB0uvf95YbA8swStFYIeyS6wN6KnraNKoqbM2qh2KVW7NjkrCkRcOQdxBvurffrtDzdecE4Td/Qygem0mHV0cOdrbWrxKaE9+W2joWhM37PTyi/ap8guDglGB3Q6yHMjecAh2Q9dEpFC1ilsX6xSmDk2/7c7W74ssbAnaZ4e1uvfDH6mprsa7moLAw=
  script: 
  - sonar-scanner -Dsonar.host.url=https://sonarqube.com -Dsonar.login=$SONAR_TOKEN
