language: java
jdk:
  - oraclejdk8
before_install:
 - chmod +x gradlew

addons:
  sonarqube: true
env:
  global:
    - secure: RpXyqKlqevqxsnMzcmnakWcc3SLQOAKSuys78MDMwwSaLdjkZdpFwQDu0dguMUg/qcjLDTS63AV+4shP6xpcWvS35COJkqcNWgtx0K2Ug59fTXByH7mNfsvAP0UlxnDSTC/SH36t5mZF/crxRvT8UxV5oj4qnsciRBfEyqDNF/eXbtbC82ZuIImxcsL3lprfWK3dZLU2sZp+En51aslKGq5sg1GzDwC6c+uNBcSKtvSBVdiGvfid1HFVlwI8VgiR7nrlgn3RcxQlUTFW7z2Dny+QX9J83NMfDRNDdA8lQzYz2VwKPnRuS9nFMhDOFjXrsl+RkUHW3+NkLVvgxci27GU+NerP8XhcM3T2lVfXn1mxRzKCYY+c1amqqT03CP1X/sp79ApeNVkG080N+2i2Mdw3bokLqAZZ7GGKxEoHzFlG8Dzj5PIGmpeA/SEi8fCPUEX2yR5TXfWl7kJnMmF851TRWAfrfE2/mKqoJsUpckO9xd4QADT43Xw1aQuGdw5UIJTB5f5L196WITjqnVAX3SXMm6MW5/xPb1TBA50cz/+ybT3KOHUkXWAkVxG/l5d61ErE+mbDcMQcQDftdaO6lKKEx4r8uJ0fFAp72AyAXxFg5rCTJ66nNVe+TfuOchYdise9xTXCMuYSf8S4uw3mlydFA4INB7nG4eJ9MxTN0/A=
  # other script steps might be done before running the actual SonarQube analysis
  - sonar-scanner -Dsonar.host.url=https://sonarqube.com -Dsonar.login=$SONAR_TOKEN
