language: java
jdk:
  - oraclejdk8
before_install:
 - chmod +x gradlew

addons:
  sonarqube: true
env:
  global:
    - secure: MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAyzxfRRq5NG8k0RxIqZ6f a9AGpGroQwzX/5FR3zML3BpHAuoh8AIU8pJmwCMQDPbymcpWEs+Tf0u9EMWNFU78 FwgCJKTOPprtRhNhZi44GgHghIABY+Z5qeYp2T4EPiwAYZhKz07AbbroJ/R3MMJx e2zRtKrxltw1WyFpVAU6jyaVNMgy6rW+zLupGW2S3BDO5gLRF+gzo1w2+6RpjWap vNbtyL8T18ozLtMjJ+dLnf5ykjZGbL5+PEa4ebX4uc9U3HY9gsiIKAkmwxEYTFMr fGeLE0+PnNR1s3t9q0LB9ZjRA6zxvz/dpBgY7ZYt0OFzD/XWJrKHdNS1JzfQfWrF G/QX47E+86PV/3zJLUATK85vIvYZG2y0oT+CPPLPs+vYA0WoF2kovxebOT+rfFIf L/wgLAv5xnqZRSUy/EmbCXsHSK4WPUwdMc0lER/731dF4o0RK10i7JdKgefI903Z AKdszYX+pK6AAYbr+KhpLuD+aYxR0h9u9zjgwcdmcHP79KXcbVmhnQpEG38dxo1I B4vjocxKaCJIs8r45hRMBf4auQFxk1LevHZnhDjx7QPy3/lfwPcOusUdtcUhVMw/ muGMWNpRx2uyPCBDV0toUpWgLcF5DxIu66BL4KUVh3rdtmxi6G10Up6evX1rufCs jgy9RHUnKbsKLlmsGnwDmj0CAwEAAQ==
  # other script steps might be done before running the actual SonarQube analysis
  - sonar-scanner -Dsonar.host.url=https://sonarqube.com -Dsonar.login=$SONAR_TOKEN
